apiVersion: dapr.io/v1alpha1
kind: Component

metadata:
  name: bindings-cocktail-updates-scheduled-queue

spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
    - name: queueName
      value: "cocktail-updates-scheduled-queue"
    - name: host
      secretKeyRef:
        name: rabbitmq_connectionstring
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: direction
      value: "input"
    - name: prefetchCount
      value: "1"
      
scopes:
  - cloudsync-api-dapr

auth:
  secretStore: secret-store