apiVersion: v1
kind: ConfigMap
metadata:
  name: cezzis-com-cloudsync-api-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
data:
  ENV: "prd"
  ACCOUNTS_API_ALLOWED_ORIGINS: "http://localhost:4001,http://localhost:4002"
  APIM_HOST_KEY: ""
  ALEMBIC_CONFIG: "/app/alembic.ini"
  AUTH0_MANAGEMENT_DOMAIN: "https://cezzis.us.auth0.com"
  AUTH0_MANAGEMENT_M2M_CLIENT_ID: "JtxZM9RiJVHejv6xqkFYdFtdfUrX6N09"
  AUTH0_DATABASE_CONNECTION_NAME: "Username-Password-Authentication"
  BLOB_STORAGE_CDN_HOSTNAME: "azure-blob.127.0.0.1.sslip.io"
  OAUTH_DOMAIN: "login.cezzis.com"
  OAUTH_AUDIENCE: "https://cezzis-cloudsync-api"
  OAUTH_CLIENT_ID: "HZXyiZxjHgkQqeb6UJxmikCGYpSz5iPb"
  OAUTH_ISSUER: "https://login.cezzis.com/"
  OAUTH_PKCE: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.openobserve-platform.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "cezzis-com-cloudsync-api"
  OTEL_SERVICE_NAMESPACE: "cezzis"
  DAPR_INIT_JOB_ENABLED: "true"
  POSTGRES_HOSTNAME: "postgres.postgres-platform.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE_NAME: "cezzis-cloudsync-db-prd"
  POSTGRES_USERNAME: "admin"
  ZOHO_SMTP_HOST: "smtppro.zoho.com"
  ZOHO_SMTP_PORT: "587"
  ZOHO_DEFAULT_SENDER_EMAIL: "cezzi@cezzis.com"
