apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cloudsync-api-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prd-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cloudsync-api-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH0_MANAGEMENT_M2M_CLIENT_SECRET: "{{ .auth0ManagementClientSecret }}"
        TEST_ACCOUNT_PASSWORD: "{{ .testAccountPassword }}"
        ZOHO_DEFAULT_SENDER_APP_PASSWORD: "{{ .zohoDefaultSenderAppPassword }}"
        STORAGE_ACCOUNT_KEY: "{{ .storageAccountKey }}"
        STORAGE_ACCOUNT_NAME: "devstoreaccount1"
        DAPR_API_TOKEN: "{{ .daprioDaprApiToken }}"
        APP_API_TOKEN: "{{ .daprioAppApiToken }}"
  data:
    - secretKey: auth0ManagementClientSecret
      remoteRef:
        key: auth0-client-secret
    - secretKey: testAccountPassword
      remoteRef:
        key: e2e-cypress-user-password
    - secretKey: zohoDefaultSenderAppPassword
      remoteRef:
        key: zoho-email-cezzi-email-app-password
    - secretKey: storageAccountKey
      remoteRef:
        key: cezzis-blob-storage-access-key-onprem
    - secretKey: daprioAppApiToken
      remoteRef:
        key: shared-daprio-app-api-token
    - secretKey: daprioDaprApiToken
      remoteRef:
        key: shared-daprio-dapr-api-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cloudsync-api-shared-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shared-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cloudsync-api-shared-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTEL_OTLP_AUTH_HEADER: "Bearer {{ .otelApiKey }}"
        POSTGRES_PASSWORD: "{{ .postgresAppPassword }}"
        RABBITMQ_CONNECTION_STRING: "amqp://cezzis-app-user-prd:{{ .rabbitmqAppPassword }}@rabbitmq.rabbitmq-platform.svc.cluster.local:5672/cezzis-prd"
  data:
    - secretKey: otelApiKey
      remoteRef:
        key: otel-collector-api-key-onprem
    - secretKey: postgresAppPassword
      remoteRef:
        key: postgres-app-password-onprem
    - secretKey: rabbitmqAppPassword
      remoteRef:
        key: rabbitmq-app-password-onprem