apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dapr-config.yaml
  - resiliency.yaml
  - bindings-cocktail-updates-queue.yaml
  - bindings-cocktail-updates-azure-queue.yaml
  - pubsub-sync-deadletter-topic.yaml
  - pubsub-cocktail-updates-sync-topic.yaml
