apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cloudsync-api-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prm-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cloudsync-api-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DAPR_API_TOKEN: "{{ .daprioDaprApiToken }}"
        APP_API_TOKEN: "{{ .daprioAppApiToken }}"
  data:
    - secretKey: daprioAppApiToken
      remoteRef:
        key: daprio-app-api-token
    - secretKey: daprioDaprApiToken
      remoteRef:
        key: daprio-dapr-api-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cloudsync-api-shared-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shared-prm-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cloudsync-api-shared-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTEL_OTLP_AUTH_HEADER: "Bearer {{ .otelApiKey }}"
        RABBITMQ_CONNECTION_STRING: "amqp://cezzis-app-user-loc:{{ .rabbitmqAppPassword }}@rabbitmq.rabbitmq-platform.svc.cluster.local:5672/cezzis-loc"
        KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1.kafka-platform.svc.cluster.local:19092"
  data:
    - secretKey: otelApiKey
      remoteRef:
        key: otel-collector-api-key
    - secretKey: rabbitmqAppPassword
      remoteRef:
        key: rabbitmq-app-password
