apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-sync-deadletter-topic
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  type: pubsub.rabbitmq
  version: v1
  initTimeout: 120s
  metadata:
    - name: exchangeName
      value: "deadletter-topic"
    - name: exchangeKind
      value: "topic"
    - name: connectionString
      secretKeyRef:
        name: cezzis-com-cloudsync-api-shared-secrets
        key: RABBITMQ_CONNECTION_STRING
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
scopes:
  - cezzis-com-cloudsync-api
auth:
  secretStore: kubernetes
