apiVersion: v1
kind: ConfigMap
metadata:
  name: cezzis-com-cloudsync-api-cloudsync-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
data:
  ENV: "prd"
  CLOUDSYNC_API_ALLOWED_ORIGINS: ""
  CLOUDSYNC_API_COCKTAIL_UPDATE_SYNC_TOPIC: "cocktails-update-topic-cloudsync"
  CLOUDSYNC_API_COCKTAIL_UPDATE_SYNC_LABEL: "cocktail-data-updated"
  CLOUDSYNC_API_COCKTAIL_UPDATE_SYNC_DAPR_BINDING: "pubsub-cocktail-updates-sync-topic-cloudsync"
  CLOUDSYNC_API_COCKTAIL_UPDATE_SYNC_DAPR_INPUT_BINDING: "bindings-cocktail-updates-azure-queue"
  OAUTH_DOMAIN: "login.cezzis.com"
  OAUTH_AUDIENCE: "https://cezzis-cloudsync-api"
  OAUTH_CLIENT_ID: "HZXyiZxjHgkQqeb6UJxmikCGYpSz5iPb"
  OAUTH_ISSUER: "https://login.cezzis.com/"
  OAUTH_PKCE: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-platform.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "cezzis-com-cloudsync-api-cloudsync"
  OTEL_SERVICE_NAMESPACE: "cezzis"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1.kafka-platform.svc.cluster.local:19092,kafka-broker-2.kafka-platform.svc.cluster.local:19093,kafka-broker-3.kafka-platform.svc.cluster.local:19095"
