apiVersion: v1
kind: Service
metadata:
  name: cezzis-com-cloudsync-api-cloudsync
  namespace: cezzis
  labels:
    app: cezzis-com-cloudsync-api-cloudsync
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "300"
spec:
  type: ClusterIP
  selector:
    app: cezzis-com-cloudsync-api-cloudsync
  ports:
    - name: http
      port: 8018
      targetPort: 8018
      protocol: TCP
